### ISSUE TITLE
Als speler wil ik kunnen interacteren met de cache zodat ik het spel kan eindigen

### ISSUE THREAD

**Issue by JaimieVos** [HU-ICT-LAB/VR-Cache#8]
Zodra je binnen handbereik komt van de cache moet het mogelijk zijn om de cache te kunnen loggen door er naar te kijken en te drukken op een knop of door de cache aan te raken.

## Taken
- [Een calculatie maken voor hoe ver de speler verwijderd is van de cache](https://github.com/HU-ICT-LAB/VR-Cache/issues/40)
- [Een manier toevoegen om het spel te laten eindigen wanneer je interacteert met de cache](https://github.com/HU-ICT-LAB/VR-Cache/issues/41)

**Comment by Alex-Jongman** [comment]
Waarom drukken op een knop, het aanraken van de cache zou toch ook voldoende kunnen zijn?
